banking_dbt:
  outputs:
    dev:
      account: jd28428.eu-west-3.aws
      database: banking
      password: Fomba@416572004
      role: accountadmin
      schema: analytics
      threads: 4
      type: snowflake
      user: Lewisb12237
      warehouse: COMPUTE_WH
  target: dev
